server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitytest?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hak
    password: hak

  jpa:
    hibernate:
      ddl-auto: none

# jwt 암호화 용 시크릿 키 등록
  jwt:
    secret: sdlfkhsdfiosadjflkjsadlksdhfhlsidhfsdflkjsdfowiehfklsdjflksdjfmcsdomsdlfksdhofihsdlkfjsdlfhsidohflksdfmsdoifjosdlkmfklsdmfsdfsdfsdlkfsdhfoisdhfklsmefklwehoilsmcsdkfhsdkufhsdfkjskdlfhosdihfisodkfjweocowencwe

