server:
  port: 8080

  servlet:
    session:
      timeout: 90m

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitytest?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hak
    password: hak

  jpa:
    hibernate:
      ddl-auto: none

  mustache:
    servlet:
      expose-request-attributes: true